version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - antfu
  - bumpp
  - defu
  - execa
  - guiiai
  - Lingtic
  - logg
  - mdast
  - neuri
  - openai
  - reactjs
  - shiki
  - shikijs
  - Streamable
  - testdata
  - typeschema
  - valibot
  - vitepress
ignoreWords: []
import: []
