version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - antfu
  - attw
  - bumpp
  - changelogithub
  - Cmpl
  - defu
  - execa
  - guiiai
  - Infobar
  - KHTML
  - Lingtic
  - lingticio
  - logg
  - mdast
  - neuri
  - noancestors
  - ofetch
  - openai
  - reactjs
  - serpapi
  - shiki
  - shikijs
  - Streamable
  - testdata
  - tsdown
  - typeschema
  - valibot
  - vitepress
  - vuejs
  - xsai
  - xsschema
ignoreWords: []
import: []
