packages:
  - packages/**
  - examples/**
  - '!**/dist/**'
  - docs

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
catalog:
  '@antfu/eslint-config': ^6.7.3
  '@antfu/ni': ^28.0.0
  '@arethetypeswrong/cli': ^0.18.2
  '@arethetypeswrong/core': ^0.18.2
  '@fetch-mock/vitest': ^0.2.18
  '@guiiai/logg': ^1.2.11
  '@types/mdast': ^4.0.4
  '@types/node': ^24.10.4
  '@unocss/eslint-config': ^66.5.10
  '@unocss/eslint-plugin': ^66.5.10
  '@vitest/coverage-v8': 4.0.16
  '@xsai-ext/providers-cloud': ^0.4.0-beta.12
  '@xsai/generate-text': ^0.4.0-beta.12
  '@xsai/shared': ^0.4.0-beta.11
  '@xsai/shared-chat': ^0.4.0-beta.11
  '@xsai/stream-text': ^0.4.0-beta.12
  '@xsai/utils-chat': ^0.4.0-beta.10
  bumpp: ^10.3.2
  changelogithub: ^14.0.0
  defu: ^6.1.4
  eslint: ^9.39.2
  eslint-plugin-import-x: ^4.16.1
  execa: ^9.6.1
  fetch-mock: ^12.6.0
  ignore: ^7.0.5
  json-schema: ^0.4.0
  nanoid: ^5.1.6
  ofetch: ^1.5.1
  remark: ^15.0.1
  serpapi: ^2.2.1
  tsdown: ^0.18.3
  tsx: ^4.21.0
  typescript: ^5.9.3
  unbuild: 3.6.1
  unocss: ^66.5.10
  unplugin-unused: ^0.5.6
  valibot: ^1.2.0
  vite: ^7.3.0
  vite-plugin-inspect: ^11.3.3
  vitepress: ^1.6.4
  vitest: ^4.0.16
  vue: ^3.5.26
  xsschema: ^0.4.0-beta.11
  zod: ^4.2.1
  zod-to-json-schema: ^3.25.0
