name: Build Previewing Docs

on:
  pull_request:
    branches:
      - main

env:
  STORE_PATH: ''

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    name: Build - ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    steps:
      # This is quite weird.
      # Eventhough this is the *intended* solution introduces in official blog post here
      # https://securitylab.github.com/research/github-actions-preventing-pwn-requests/.
      # But still, as https://github.com/orgs/community/discussions/25220#discussioncomment-7856118 stated,
      # this is vulnerable since there is no source of truth about which PR in the triggered workflow.
      - name: Presist PR number
        run: |
          echo "${{ github.event.number }}" > pr_num

      - name: Upload PR artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr-num
          path: ./pr_num

      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm build:packages
        env:
          # As suggested in Verbose Build option to be able to track down errors https://github.com/vuejs/vitepress/issues/422
          # vitepress build command does not have --debug option, so we need to set it manually where the debug package is used.
          DEBUG: '*'

      - name: Build docs
        run: pnpm build:docs

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-${{ matrix.os }}-build
          path: docs/.vitepress/dist
