name: CI

on:
  push:
    paths-ignore:
      - 'docs/pages/**'
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'docs/pages/**'
    branches:
      - main

jobs:
  unittest:
    strategy:
      matrix:
        node-version: ['20.x', '22.x']

    name: Unit tests - ${{ matrix.node-version }}
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: Build packages
        run: pnpm run packages:build

      - name: Test
        run: pnpm run test
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_BASEURL: ${{ secrets.OPENAI_API_BASEURL }}
          SERPAPI_API_KEY: ${{ secrets.SERPAPI_API_KEY }}

  lint:
    name: Lint
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: Lint
        run: pnpm run lint

  packages-build-test:

    name: Packages Build Test
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: Build packages
        run: |
          pnpm run packages:build
          pnpm run packages:attw
