name: Build Docs to Netlify

on:
  push:
    branches:
      - 'main'

env:
  STORE_PATH: ''

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    environment:
      name: Production Docs
      url: https://docs.neuri.ai
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build docs
        run: |
          pnpm build:packages
          pnpm build:docs
        env:
          # As suggested in Verbose Build option to be able to track down errors https://github.com/vuejs/vitepress/issues/422
          # vitepress build command does not have --debug option, so we need to set it manually where the debug package is used.
          # DEBUG: 'vitepress:*'
          VUE_PROD_HYDRATION_MISMATCH_DETAILS_FLAG: '1'

      - name: Install Netlify CLI
        run: pnpm install -g netlify-cli

      - name: Push to Netlify
        timeout-minutes: 10
        working-directory: docs/
        run: |
          netlify deploy --dir 'docs/.vitepress/dist' --prod --debug
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
