name: Release

on:
  push:
    tags:
      - 'v*'

env:
  STORE_PATH: ''

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write
  packages: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v5
        with:
          cache: pnpm
          node-version: latest
          registry-url: https://registry.npmjs.org

      - name: Install
        run: pnpm i

      - name: Packages build
        run: pnpm run build:packages

      - name: Packages publish
        run: pnpm run publish:packages
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Sync GitHub Release
        run: pnpm run changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
